NO_FORMAT="\033[0m"
F_BOLD="\033[1m"
C_RED3="\033[38;5;203m"
F_DIM="\033[2m"

printf "${C_RED3}⣿⣿⣿⠟⠛⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⢋⣩⣉⢻⣿⣿\n"
printf "⣿⣿⣿⠀⣿⣶⣕⣈⠹⠿⠿⠿⠿⠟⠛⣛⢋⣰⠣⣿⣿⠀⣿⣿\n"
printf "⣿⣿⣿⡀⣿⣿⣿⣧⢻⣿⣶⣷⣿⣿⣿⣿⣿⣿⡿⠶⡝⠀⣿⣿\n"
printf "⣿⣿⣿⣷⠘⣿⣿⣿⢏⣿⣿⣋⣀⣈⣻⣿⣿⣷⣧⣤⣿⡐⢿⣿\n"
printf "⣿⣿⣿⣿⣆⢩⣝⣫⣾⣿⣿⣿⣿⡟⠿⠿⠦⢸⠸⠿⣻⣿⡄⢻\n"
printf "⣿⣿⣿⣿⣿⡄⢻⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⠇⣼\n"
printf "⣿⣿⣿⣿⣿⣿⡄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣰⣿\n"
printf "⣿⣿⣿⣿⣿⣿⠇⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢀⣿⣿\n"
printf "⣿⣿⣿⣿⣿⠏⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿\n"
printf "⣿⣿⣿⣿⠟⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿\n"
printf "⣿⣿⣿⠋⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⣿⣿\n"
printf "⣿⣿⠋⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿${NO_FORMAT}\n\n"

printf "${F_BOLD}${C_RED3}ruth@santana ---------------------------------------------${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. OS ${F_DIM}.............................. ${NO_FORMAT} MacOS Sequoia, iOS 17\n"
printf "${F_BOLD}${C_RED3}. Studying ${F_DIM}...... ${NO_FORMAT} Defold, Artificial Intelligence, Hebrew\n"
printf "${F_BOLD}${C_RED3}. ${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. Languages.Favourite ${F_DIM}........................ ${NO_FORMAT} Typescript\n"
printf "${F_BOLD}${C_RED3}. Languages.Programming ${F_DIM}.................. ${NO_FORMAT} Dart, Lua, C++\n"
printf "${F_BOLD}${C_RED3}. Languages.Natural ${F_DIM}................. ${NO_FORMAT} English, Portuguese\n"
printf "${F_BOLD}${C_RED3}. ${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. Hobbies.Software ${F_DIM}....... ${NO_FORMAT} Game Modding, Game Development\n"
printf "${F_BOLD}${C_RED3}. Hobbies.Hardware ${F_DIM}.......................... ${NO_FORMAT} 3D Printing\n"
printf "${F_BOLD}${C_RED3}. ${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. Email.Work ${F_DIM}........................ ${NO_FORMAT} cs.ruth@outlook.com\n"
printf "${F_BOLD}${C_RED3}. Discord ${F_DIM}...................................... ${NO_FORMAT} @cs.ruth\n"
printf "${F_BOLD}${C_RED3}----------------------------------------------------------${NO_FORMAT}\n"
