NO_FORMAT="\033[0m"
F_BOLD="\033[1m"
C_RED3="\033[38;5;160m"

printf "${C_RED3}⣿⣿⣿⠟⠛⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⢋⣩⣉⢻⣿⣿\n"
printf "⣿⣿⣿⠀⣿⣶⣕⣈⠹⠿⠿⠿⠿⠟⠛⣛⢋⣰⠣⣿⣿⠀⣿⣿\n"
printf "⣿⣿⣿⡀⣿⣿⣿⣧⢻⣿⣶⣷⣿⣿⣿⣿⣿⣿⡿⠶⡝⠀⣿⣿\n"
printf "⣿⣿⣿⣷⠘⣿⣿⣿⢏⣿⣿⣋⣀⣈⣻⣿⣿⣷⣧⣤⣿⡐⢿⣿\n"
printf "⣿⣿⣿⣿⣆⢩⣝⣫⣾⣿⣿⣿⣿⡟⠿⠿⠦⢸⠸⠿⣻⣿⡄⢻\n"
printf "⣿⣿⣿⣿⣿⡄⢻⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⠇⣼\n"
printf "⣿⣿⣿⣿⣿⣿⡄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣰⣿\n"
printf "⣿⣿⣿⣿⣿⣿⠇⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢀⣿⣿\n"
printf "⣿⣿⣿⣿⣿⠏⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿\n"
printf "⣿⣿⣿⣿⠟⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿\n"
printf "⣿⣿⣿⠋⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⣿⣿\n"
printf "⣿⣿⠋⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿${NO_FORMAT}\n\n"

printf "${F_BOLD}${C_RED3}ruth@santana ---------------------------------------------${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. OS .............................. ${NO_FORMAT} MacOS Sequoia, iOS 17\n"
printf "${F_BOLD}${C_RED3}. Studying ...... ${NO_FORMAT} Defold, Artificial Intelligence, Hebrew\n"
printf "${F_BOLD}${C_RED3}. ${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. Languages.Favourite ........................ ${NO_FORMAT} Typescript\n"
printf "${F_BOLD}${C_RED3}. Languages.Programming .................. ${NO_FORMAT} Dart, Lua, C++\n"
printf "${F_BOLD}${C_RED3}. Languages.Natural ................. ${NO_FORMAT} English, Portuguese\n"
printf "${F_BOLD}${C_RED3}. ${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. Hobbies.Software ....... ${NO_FORMAT} Game Modding, Game Development\n"
printf "${F_BOLD}${C_RED3}. Hobbies.Hardware .......................... ${NO_FORMAT} 3D Printing\n"
printf "${F_BOLD}${C_RED3}. ${NO_FORMAT}\n"
printf "${F_BOLD}${C_RED3}. Email.Work ........................ ${NO_FORMAT} cs.ruth@outlook.com\n"
printf "${F_BOLD}${C_RED3}. Discord ...................................... ${NO_FORMAT} @cs.ruth\n"
printf "${F_BOLD}${C_RED3}----------------------------------------------------------${NO_FORMAT}\n"
